// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://agteqxoqqbkonwiqdaam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFndGVxeG9xcWJrb253aXFkYWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTI5MjMsImV4cCI6MjA3NDUyODkyM30.5YEFNeRfD9Gi_WeD14GoCOHXQjkmXENmrhYz7YMinis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});